### ISSUE TITLE
subcommand help doesn't show subcommand

### ISSUE THREAD

**Issue by kewisch** [druths/arghandler#5]
Thanks for fixing my other issues so quickly! I found another minor issue in the help text.

mytool -h shows something like:

```
usage: mytool [-h] {sub1,sub2}

positional arguments:
  {sub1,sub2}
  cargs                 arguments for the subcommand

optional arguments:
  -h, --help            show this help message and exit
```

This is correct so far, now let's look at `mytool sub1 -h`:

```
usage: mytool [-h] [-m MESSAGE] subarg

positional arguments:
  subarg                 some positional argument for the subcommand       

optional arguments:
  -h, --help  show this help message and exit
 -m MESSAGE, --message MESSAGE
                        description for the message parameter
```

It looks like the subcommand help text is missing the subcommand name, I'd expect this to be included:

```
usage: mytool sub1 [-h] [-m MESSAGE] subarg
```

**Comment by druths** [comment]
Hmmm... For this to happen, the subcommand argument parser/handler object would need to know that it's a subcommand parser. Possibly the best pattern here would be to pass in an argparser into the subcommand function that was preconfigured with this knowledge. What are your thoughts about this?

(For the time being, btw, you can set that prefix using the "prog" argument of the ArgumentParser constructor.)

**Comment by druths** [comment]
Ok - I've added this functionality.  Now subcommands take _three_ arguments:
- parser - an ArgumentParser that is pre-prepared with the correct prog field.
- context - the usual
- args - the usual

Basically, just use the parser in subcommands.  See the README and tests for examples.

Since this breaks the previous contract for subcommands, I bumped the minor version ... probably should have bumped the major version, but these are early days, so I don't want to run up the major version too quickly!  Update from pypi or the repo.
